### ISSUE TITLE
Do not display color key if color not defined

### ISSUE THREAD

**Issue by gvwilson** [tidyblocks/briq#91]
1. Drag out `penguins` dataset.
2. Create scatter plot named `stuff` with X axis set to `bill_length_mm` and Y axis set to `flipper_length_mm`. Leave the color box set to `color` (the default, meaning "no color") and check the "show line" box.

Resulting plot has a key showing the color for "undefined". This shouldn't be there (and if a key _is_ present, it shouldn't overflow the side of the display).
![Screen Shot 2020-07-30 at 1 42 39 PM](https://user-images.githubusercontent.com/911566/88956200-01b20900-d26b-11ea-8b08-5d1e8e1998b9.png)

**Comment by MayaGans** [comment]
Originally I thought this would be easy - if the color input == "color" then don't add a color since that's the default value. 
But I wanted to brain storm with you because there will eventually be a use case where the user's column name IS "color"
Can I change the default input to ".color"? That seems a little brute force-ish though.... Any other ideas?

**Comment by MayaGans** [comment]
does `TransformScatter` "know" about the data, can I check if there's a column name called "color"?

**Comment by MayaGans** [comment]
I want to do something like if (Object.keys(data.values).includes(color)) { plot with color } 
But I don't think data exists inside the transform?

**Comment by MayaGans** [comment]
Closed with #96
